# resolver 17-15 for ghc-8.10.4
resolver: lts-17.15

# User packages to be built.
packages:
  - xmobar-git
  - xmonad-git
  - xmonad-contrib-git


# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
extra-deps:
  - iwlib-0.1.0
  - parsec-numbers-0.1.0
  - libmpd-0.9.0.9
  - alsa-mixer-0.3.0

# Override default flag values for local packages and extra-deps
flags:
  xmobar:
    all_extensions: true
